remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Recipes and Ratings]
description: [Here, we explore regression and predict the number of calories in a model.]